### PR TITLE
Sana - script for generating spectograms

### PR DESCRIPTION
**Pull request by sc4789**
in VM, wrote a script for creating all spectograms for the audio files. -Sanmati

### CODE REVIEW

**Review by stevenwinnick — COMMENTED** [review]
What was the reason for splitting it into chunks like that?

**Comment by sc4789** [comment]
> What was the reason for splitting it into chunks like that?

Due to the amount of data, the kernel kept dying and restarting so I did it in batches so that we could store them!

**Comment by preethiprakash1** [comment]
How did you decide on the time cutoff value? Was the entire audio file too large to process?

**Comment by sc4789** [comment]
> How did you decide on the time cutoff value? Was the entire audio file too large to process?

Yes, 10 seconds worked well because I would get errors above 15 seconds

**Comment by sc4789** [comment]
> What was the reason for splitting it into chunks like that?

It was to ensure that the kernel wouldn't crash given 28000 files !

**Pull request merged**
